### ISSUE TITLE
Compilation error on solaris 11.3 while building icu 70.1

### ISSUE THREAD

**Issue by Hanumesh96** [unicode-org/icu-jira-safari#2]
Hi,
Iam facing below error while building ICU 70.1 using "oracle developer studio 12.6" on solaris "SunOS 11.3 sun4v sparc".

<<<

escapesrc: /icu_70_1_build/icu/source/i18n/compactdecimalformat.cpp -> _compactdecimalformat.cpp
/comms/tools/apps/solarisstudio126_sparc/bin/CC   -DU_DEBUG=1 -DU_HAVE_ELF_H=1 -DU_HAVE_STRTOD_L=0  -I/icu_70_1_build/icu/source/i18n -I/icu_70_1_build/icu/source/common   -DU_ATTRIBUTE_DEPRECATED= -DU_I18N_IMPLEMENTATION -xarch=sparc -m64 -norunpath -g -Wno-ambiguous-reversed-operator -mt  -std=c++11  -c -DPIC -KPIC -o compactdecimalformat.o _compactdecimalformat.cpp
**"/icu_70_1_build/icu/source/i18n/formatted_string_builder.h", line 235: Error: Initializer for constexpr variable icu_70::kUndefinedField must be a constant expression.
"/icu_70_1_build/icu/source/i18n/formatted_string_builder.h", line 240: Error: Initializer for constexpr variable icu_70::kGeneralNumericField must be a constant expression.**
"/icu_70_1_build/icu/source/common/static_unicode_sets.h", line 130: Warning: Too many characters in character constant u'£'.
"/icu_70_1_build/icu/source/common/static_unicode_sets.h", line 131: Warning: Too many characters in character constant u'₹'.
"/icu_70_1_build/icu/source/common/static_unicode_sets.h", line 132: Warning: Too many characters in character constant u'¥'.
"/icu_70_1_build/icu/source/common/static_unicode_sets.h", line 133: Warning: Too many characters in character constant u'₩'.
"/icu_70_1_build/icu/source/i18n/numparse_impl.h", line 38: Warning: Function icu_70::numparse::impl::NumberParserImpl::~NumberParserImpl() can throw only the exceptions thrown by the function icu_70::numparse::impl::MutableMatcherCollection::~MutableMatcherCollection() it overrides.
2 Error(s) and 5 Warning(s) detected.
gmake[2]: *** [compactdecimalformat.o] Error 2

>>>

For me everything looks fine and also builds successfully on linux platform.

Your help to resolve this issue will be greatly appreciated.

Many Thanks,
Hanumesh

**Comment by markusicu** [comment]
Hi Hanumesh, this is not an active repo. Please send usage questions to the icu-support mailing list. https://icu.unicode.org/contacts
